{
 "title": "全球节点监控",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "尼日利亚(西非) 拉各斯",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "SUNMI_APP_API_check{country='NG'}",
     "legendFormat": "APP_API 访问速度 (ms)"
    },
    { "expr": "GUANWANG_check{country='NG'}", "legendFormat": "官网访问速度 (ms)" },
    { "expr": "PARTNER_check{country='NG'}", "legendFormat": "合作伙伴访问速度 (ms)" },
    {
     "expr": "SUNMI_WEB_API_check{country='NG'}",
     "legendFormat": "WEB_API访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SH_check{country='NG'}",
     "legendFormat": "金山云上海访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SZ_check{country='NG'}",
     "legendFormat": "金山云深圳访问速度 (ms)"
    }
   ]
  },
  {
   "title": "尼日利亚(西非) 拉各斯",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "expr": "cdn_check{country='NG'}", "legendFormat": "文件下载" },
    { "expr": "upload_check{country='NG'}", "legendFormat": "文件上传" }
   ]
  },
  {
   "title": "印度(南亚) 孟买",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "SUNMI_APP_API_check{country='IN'}",
     "legendFormat": "APP_API 访问速度 (ms)"
    },
    { "expr": "GUANWANG_check{country='IN'}", "legendFormat": "官网访问速度 (ms)" },
    { "expr": "PARTNER_check{country='IN'}", "legendFormat": "合作伙伴访问速度 (ms)" },
    {
     "expr": "SUNMI_WEB_API_check{country='IN'}",
     "legendFormat": "WEB_API访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SH_check{country='IN'}",
     "legendFormat": "金山云上海访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SZ_check{country='IN'}",
     "legendFormat": "金山云深圳访问速度 (ms)"
    }
   ]
  },
  {
   "title": "印度(南亚) 孟买",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "expr": "cdn_check{country='IN'}", "legendFormat": "文件下载" },
    { "expr": "upload_check{country='IN'}", "legendFormat": "文件上传" }
   ]
  },
  {
   "title": "阿拉伯(中东) 迪拜",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "SUNMI_APP_API_check{country='AE'}",
     "legendFormat": "APP_API 访问速度 (ms)"
    },
    { "expr": "GUANWANG_check{country='AE'}", "legendFormat": "官网访问速度 (ms)" },
    { "expr": "PARTNER_check{country='AE'}", "legendFormat": "合作伙伴访问速度 (ms)" },
    {
     "expr": "SUNMI_WEB_API_check{country='AE'}",
     "legendFormat": "WEB_API访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SH_check{country='AE'}",
     "legendFormat": "金山云上海访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SZ_check{country='AE'}",
     "legendFormat": "金山云深圳访问速度 (ms)"
    }
   ]
  },
  {
   "title": "印度(南亚) 孟买",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "SUNMI_APP_API_check{country='IN'}",
     "legendFormat": "APP_API 访问速度 (ms)"
    },
    { "expr": "GUANWANG_check{country='IN'}", "legendFormat": "官网访问速度 (ms)" },
    { "expr": "PARTNER_check{country='IN'}", "legendFormat": "合作伙伴访问速度 (ms)" },
    {
     "expr": "SUNMI_WEB_API_check{country='IN'}",
     "legendFormat": "WEB_API访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SH_check{country='IN'}",
     "legendFormat": "金山云上海访问速度 (ms)"
    },
    {
     "expr": "SUNMI_KMS_SZ_check{country='IN'}",
     "legendFormat": "金山云深圳访问速度 (ms)"
    }
   ]
  }
 ]
}